
image:
  repository: sonarqube
  tag: 9.2-community

# List of plugins to install.
# For example:
# plugins:
#  install:
#    - "https://github.com/AmadeusITGroup/sonar-stash/releases/download/1.3.0/sonar-stash-plugin-1.3.0.jar"
#    - "https://github.com/SonarSource/sonar-ldap/releases/download/2.2-RC3/sonar-ldap-plugin-2.2.0.601.jar"
plugins:
  install: []
  lib: []

resources: 
  limits:
    cpu: 500m
    memory: 2Gi
  requests:
    cpu: 100m
    memory: 512Mi
persistence:
  enabled: false
  annotations: {}
  storageClass:
  accessMode: ReadWriteOnce
  size: 10Gi


createPostgresqlSecret: true
# create the postgresql secret in Sonarqube chart, outside of the postgresql chart.

postgresql:
  # Enable to deploy the PostgreSQL chart
  enabled: true
  persistence:
    enabled: false
